### ISSUE TITLE
can't read 3d seismic segy data 

### ISSUE THREAD

**Issue by jpgithub1310** [sixty-north/segpy#32]
Hi,
I am trying to read a small 3D segy file, unfortunayely it does not understand it to be 3D!
Dimesionality given is 0 and it does not understand  inlines and xlines in the header.

python program ::
---------------------------------------------------------------------------------------------------------
#
import argparse
import os
import sys
import traceback
	
import numpy as np
from segpy.reader import *
from segpy_numpy.dtypes import make_dtype
#

with open('TEST.sgy', 'rb') as segy:

    segy_reader = create_reader(segy)

    print("Dimensionality: ", segy_reader.dimensionality)
#    print("Header: ", segy_reader.trace_header(0))

    print("Number of traces: ", segy_reader.num_traces())
    print("DATA_SAMPLE_FORMAT: ", segy_reader.data_sample_format)
    print("Filename: ", segy_reader.filename)
    print("SEG Y revision: ", segy_reader.revision)

    print("inine: ",segy_reader.num_inlines())

    print("inine: ",segy_reader.num_xlines())

---------------------------------------------------------------------------------------------------------
following is the error:
---------------------------------------------------------------------------------------------------------
Dimensionality:  0
Number of traces:  7
DATA_SAMPLE_FORMAT:  float32
Filename:  TEST.sgy
SEG Y revision:  0
Traceback (most recent call last):
  File "test3.py", line 25, in <module>
    print("inine: ",segy_reader.num_inlines())
AttributeError: 'SegYReader' object has no attribute 'num_inlines'
-----------------------------------------------------------------------------------------

The python file to read and the small 3D segy file is attached for your reference.

**Comment by rob-smallshire** [comment]
The SEG Y file doesn't seem to be attached.

**Comment by jpgithub1310** [comment]
Hi
Please find the attached programm and segy data.

Regards
JP Yadav
[segyread-data.zip](https://github.com/sixty-north/segpy/files/849766/segyread-data.zip)

**Comment by rob-smallshire** [comment]
The file has seven traces. What geometry do you expect it to have? 1 inline x 7 crosslines, or something else?

**Comment by jpgithub1310** [comment]
This data was intended to test the code and hence it is a simple one 1 iline X 7 xline. I tested with a 51 ilines X 101 xlines, still it spits out the same error. 
I feel that I am not able to make the code  understand that the data is 3D and hence all headers pertinent to 3D seismic data is not visible in the header output of the code.

**Comment by rob-smallshire** [comment]
I've made a change in fdd6c3771877cab7ac069fbbd1f80fcefea64d6b to the heuristic used by *Segpy* to determine whether data in a file is 2D or 3D. With this change your example file is detected as 3D with one inline and one crossline.

You'll need to install a version of Segpy from the version on Github.

**Comment by khawar85** [comment]
Dear Support / Helping officer /brother

Good afternoon. I am facing a problem in 3D segy reading. Can you help me why this error is? Please

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/segpy/header.py in __set__(self, instance, value)
    298         try:
--> 299             self._instance_data[instance] = self._named_field._value_type(value)
    300         except ValueError as e:

~/.local/lib/python3.5/site-packages/segpy/field_types.py in class_new(cls, *args, **kwargs)
     13                 cls.__name__, instance,
---> 14                 cls.MINIMUM, cls.MAXIMUM))
     15         return instance

ValueError: NNInt16 value 51614 outside range 0 to 32767

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-2-e6863cf15467> in <module>()
     19 
     20 f=open(file_near, 'rb')
---> 21 segy = create_reader(f)
     22 
     23 ntraces  = segy.num_traces()

~/.local/lib/python3.5/site-packages/segpy/reader.py in create_reader(fh, encoding, binary_reel_header_format, trace_header_format, endian, progress, cache_directory, dimensionality)
    151     if reader is None:
    152         reader = _make_reader(fh, encoding, binary_reel_header_format, trace_header_format,
--> 153                               endian, progress_callback, dimensionality)
    154         if cache_file_path is not None:
    155             _save_reader_to_cache(reader, cache_file_path)

~/.local/lib/python3.5/site-packages/segpy/reader.py in _make_reader(fh, encoding, binary_reel_header_format, trace_header_format, endian, progress, dimensionality)
    256         encoding = ASCII
    257     textual_reel_header = read_textual_reel_header(fh, encoding)
--> 258     binary_reel_header = read_binary_reel_header(fh, binary_reel_header_format, endian=endian)
    259     extended_textual_header = read_extended_textual_headers(fh, binary_reel_header, encoding)
    260     bps = bytes_per_sample(binary_reel_header)

~/.local/lib/python3.5/site-packages/segpy/toolkit.py in read_binary_reel_header(fh, binary_reel_header_format, endian)
    180     header_packer = make_header_packer(binary_reel_header_format, endian)
    181     buffer = fh.read(binary_reel_header_format.LENGTH_IN_BYTES)
--> 182     reel_header = header_packer.unpack(buffer)
    183     return reel_header
    184 

~/.local/lib/python3.5/site-packages/segpy/packer.py in unpack(self, buffer)
    198                                          str(e).capitalize())) from e
    199         else:
--> 200             return self._unpack(values)
    201 
    202     @abstractmethod

~/.local/lib/python3.5/site-packages/segpy/packer.py in _unpack(self, values)
    222 
    223     def _unpack(self, values):
--> 224         return self._header_format_class(*values)
    225 
    226 

~/.local/lib/python3.5/site-packages/segpy/header.py in __init__(self, *args, **kwargs)
     29         """
     30         for keyword, arg in zip(self.ordered_field_names(), args):
---> 31             setattr(self, keyword, arg)
     32 
     33         for keyword, arg in kwargs.items():

~/.local/lib/python3.5/site-packages/segpy/header.py in __set__(self, instance, value)
    300         except ValueError as e:
    301             raise ValueError("Assigned value {!r} for {} attribute must be convertible to {}: {}"
--> 302                              .format(value, self._name, self._named_field._value_type.__name__, e)) from e
    303 
    304     def __delete__(self, instance):

ValueError: Assigned value 51614 for ensemble_fold attribute must be convertible to NNInt16: NNInt16 value 51614 outside range 0 to 32767

**Comment by rob-smallshire** [comment]
@khawar85 Can you please create a new issue for this, rather than reopening an old issue.
