### ISSUE TITLE
Can not install the package?

### ISSUE THREAD

**Issue by youlimao** [sixty-north/segpy#46]
To whom it may concern:
 
I am new to Python and currently working on a project which needs to read SEGY data. I am currently using Anaconda on Windows. 
I tried two ways to install it:
1, download the package and unzip the segy.zip file and run : python setup.py install
2, pip install git+https://github.com/sixty-north/segpy.git
after installation, both tries give me the follow message:
.................................................................................
requirement already satisfied

But the real package segpy is not installed actually? I can not find it in my anaconda environment. Did I do something wrong? 

Best,

Youli

**Comment by pareantoine** [comment]
Hi Youli,

The anaconda navigator will not show SEGPY in the navigaotor as you did not install it with anaconda.

But, open a terminal and type "conda list".
Segpy should be listed there.

Another test, if you open a python console and type "import numpy", do you get an error returned?

Antoine

**Comment by youlimao** [comment]
Hi, Antonie
 
Thanks for your reply!I really appreciate it.

 I actually checked the 'conda list' and could not find it segpy package there.

Please see the screen shots here(1, conda list;2, after installation):
![screencapture](https://cloud.githubusercontent.com/assets/28906575/26403629/88ec6700-4054-11e7-95a3-a9627b33fc54.PNG)
![screencapture2](https://cloud.githubusercontent.com/assets/28906575/26403630/88f7c096-4054-11e7-9ce7-d83107873a92.PNG)

Best,

Youli

**Comment by bwulff** [comment]
I'm experiencing problems with the package in Python 3:
```bash
$ pip install segpy
Collecting segpy
  Downloading segpy-2.0.0a2-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 652kB/s 
Installing collected packages: segpy
Successfully installed segpy-2.0.0a2
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import segpy
>>> print(segpy.__version__)
2.0.0a2
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import segpy
>>> print(segpy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'segpy' has no attribute '__version__'
```
also when I try to run an example
```bash
python3 timeslice.py waipuku.sgy output.npy 100
Traceback (most recent call last):
  File "timeslice.py", line 35, in <module>
    from segpy.reader import create_reader
ImportError: No module named 'segpy.reader'
```
Since I get no import error in Python 2 I'm trying to convert the timeslice example to Py2 and see if it works there.

**Comment by rob-smallshire** [comment]
Segpy is explicitly **not** compatible with Python 2.

The version of `segpy` on PyPI is quite old, so to get the latest version you need to install the version here on GitHub.  The best way to do this is:

    pip install git+https://github.com/sixty-north/segpy.git#egg=segpy

At some point I'll get around to uploading a new version to PyPI.

**Comment by youlimao** [comment]
I ended up using another package which worked for me.
