### ISSUE TITLE
Fix invalid license change in `segpy-lite`

### ISSUE THREAD

**Issue by abingham** [sixty-north/segpy#61]
Since the `segpy-lite` fork has no issue tracker, I'm putting this issue in here, in the upstream repo.

In commit d8132ed8d68c368502a64760ce801024feaffd3a on [the `segpy-lite` fork](https://github.com/whimian/segpy-lite) of `segpy`, @whimian changed the license of the fork from AGPL to MIT. This appears to be in violation of section 5 of the AGPL, and we need the license to be changed back to AGPL.

@whimian Was this change made in order to facilitate inclusion in anaconda? We would like to support the inclusion of segpy in anaconda, but we can't allow the license to be changed like this.

**Comment by whimian** [comment]
Then I will change the license to AGPL.

**Comment by abingham** [comment]
Thanks!

**Comment by abingham** [comment]
Fixed in 7f270aa05d6fed5e35321c7405f11f36604f64c4

**Comment by rob-smallshire** [comment]
Hi @whimian. I'm curious why segpy-lite is necessary.  What changes would be needed to *segpy* to meet your needs?
